language: python
python:
- '3.6'

before_install:
- sudo rm -f /etc/boto.cfg

cache: pip
install:
- pip install -r requirements.txt

branches:
  only:
  - master
  - development

jobs:
  include:
  - stage: Running Unit Tests
    name: Unit Tests
    script:
    - pytest
  
notifications:
  slack:
    rooms:
    - texasspacecraftlab:pM977JUdiMXelhhpRZBgWvN2#builds
    on_success: always
    on_failure: always